import { cssr } from 'dsh-tauri-ui/client'

const { c, bem: { b, e, m } } = cssr

/** 侧栏整槽克隆（sidebar.tsx）：root + logo 行 + 面板区 + 官方子槽透传 + 折叠态。 */
export default b('panel', {
  '--dshp-padding': '12px',
  'height': '100%',
  'padding': '6px var(--dshp-padding)',
  'boxSizing': 'border-box',
  'background': 'var(--dsw-specific-sidebar-fill)',
  'color': 'var(--dsw-alias-label-primary)',
  '--dsh-scrollbar-thumb': 'var(--dsw-alias-scrollbar-bg-l2)',
  '--dsh-scrollbar-thumb-hover': 'var(--dsw-alias-scrollbar-hover-l2)',
  'flexDirection': 'column',
  'fontSize': '14px',
  'display': 'flex',
  '--dsh-sidebar-inline-padding': 'var(--dshp-padding)',
}, [
  e('logo-row', {
    boxSizing: 'border-box',
    flex: 'none',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '8px',
    height: '60px',
    marginBottom: '4px',
    padding: '4px 0 4px 4px',
    display: 'flex',
    overflow: 'hidden',
  }),
  e('brand', {
    minWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    flex: 1,
    alignItems: 'center',
    padding: 0,
    display: 'inline-flex',
    overflow: 'hidden',
  }),
  e('brand-identity', {
    alignItems: 'center',
    gap: '8px',
    minWidth: 0,
    height: '24px',
    display: 'inline-flex',
  }),
  e('brand-mark', {
    flex: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
  }),
  e('brand-name', {
    letterSpacing: '.04em',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    height: '24px',
    fontSize: '18px',
    fontWeight: 600,
    lineHeight: '24px',
    display: 'inline-flex',
  }),
  e('fallback-brand-name', {
    letterSpacing: 0,
    whiteSpace: 'nowrap',
    fontSize: '17px',
  }),
  e('icon-button', {
    cursor: 'pointer',
    width: '28px',
    height: '28px',
    color: 'var(--dsw-alias-label-secondary)',
    background: 'transparent',
    border: 'none',
    borderRadius: '50%',
    flex: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    display: 'inline-flex',
  }, [
    c('&:hover', { background: 'var(--dsw-alias-interactive-bg-hover)' }),
  ]),
  e('rail-mark', {
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
  }),
  e('panel-area', {
    flex: 'none',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '2px',
    margin: 0,
    display: 'flex',
    marginRight: 'var(--dsh-session-list-scrollbar-offset)',
    paddingLeft: '4px',
    paddingRight: 'calc(var(--dsh-session-list-edge-inset) - var(--dsh-session-list-scrollbar-width) - var(--dsh-session-list-scrollbar-offset))',
  }),
  // 官方全局面板清单（sidebar.panellist，0.1.5-rc.2）：行本体复用 .dshp-panel__menu-item
  // （与私有协议条目同一份视觉），这里只负责把清单本身排成与 panel-area 同节奏的列，
  // 保证「新会话 → 官方全局面板 → 私有功能项」间距一致。
  e('panel-list', {
    flex: 'none',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '2px',
    margin: 0,
    padding: 0,
    display: 'flex',
  }),
  // 新会话按钮是独立控件，不再挂 .dshp-panel__menu-item（那是面板区第三方功能项
  // 的行样式，51c0195 拆分样式后 action-item.cssr 后挂载，同特异性下会把本块的
  // 白底/圆角/描边全部覆盖成透明菜单行）。这里自给自足地镜像官方 ui-sidebar 的
  // New Session 按钮（.hHd-Xa_newSession：elevated-fill 白底、12px 圆角、
  // .5px l3 描边、38px 高、500 字重），并补上按钮交互基座
  // （appearance/cursor/focus-visible/transition）。
  e('new-session', {
    boxSizing: 'border-box',
    appearance: 'none',
    cursor: 'pointer',
    userSelect: 'none',
    width: '100%',
    minWidth: 0,
    height: '38px',
    flex: 'none',
    margin: '0 0 4px',
    padding: '8px 16px',
    border: '.5px solid var(--dsw-alias-border-l3)',
    borderRadius: '12px',
    background: 'var(--dsw-alias-button-elevated-fill)',
    color: 'var(--dsw-alias-label-primary)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '6px',
    fontFamily: 'inherit',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '22px',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    transition: 'background-color .12s var(--ds-ease-in-out), color .12s var(--ds-ease-in-out)',
  }, [
    c('&:hover', { background: 'var(--dsw-alias-button-floating-hover)' }),
    c('&:focus-visible', { outline: '2px solid var(--dsw-alias-border-focus)', outlineOffset: '-2px' }),
  ]),
  e('region-area', {
    minHeight: 0,
    marginRight: 'calc(-1 * var(--dshp-padding))',
    flexDirection: 'column',
    flex: 1,
    padding: '0 4px',
    display: 'flex',
    overflow: 'hidden',
  }),
  e('foot-area', {
    flexDirection: 'column',
    flex: 'none',
    display: 'flex',
  }),
  e('footer-actions', {
    flex: 'none',
    width: '100%',
    minWidth: 0,
    display: 'flex',
  }),
  e('settings-area', {
    flex: 'none',
    width: '100%',
    minWidth: 0,
  }),
  m('collapsed', [
    c('&', { padding: '18px 10px 6px' }),
    c('& .dshp-panel__logo-row', { justifyContent: 'flex-start', height: '40px', marginBottom: '4px', padding: 0 }),
    c('& .dshp-panel__icon-button', { width: '36px', height: '36px', color: 'var(--dsw-alias-label-primary)' }),
    c('& .dshp-panel__panel-area', { alignItems: 'center', gap: '4px', marginBottom: '12px', paddingLeft: 0 }),
    c('& .dshp-panel__menu-item', {
      justifyContent: 'center',
      alignSelf: 'flex-start',
      width: '36px',
      minWidth: '36px',
      height: '36px',
      padding: 0,
      gap: 0,
      borderRadius: '12px',
    }),
    c('& .dshp-panel__menu-item-label', { display: 'none' }),
    c('& .dshp-panel__menu-item-icon', {
      fontSize: '18px',
      color: 'var(--dsw-alias-label-primary)',
    }),
    c('& .dshp-panel__new-session', {
      borderColor: 'transparent',
      justifyContent: 'center',
      width: '36px',
      height: '36px',
      margin: 0,
      padding: 0,
      gap: 0,
    }),
    c('& .dshp-panel__region-area', { marginLeft: 0, marginRight: 0, padding: 0 }),
    c('& .dshp-panel__foot-area', { alignItems: 'center' }),
    c('& .dshp-panel__settings-area, & .dshp-panel__footer-actions', { justifyContent: 'center', width: 'auto', display: 'flex' }),
  ]),
  m('wide', [
    c('&', { width: 'var(--dshp-width)' }),
  ]),
  m('quiet-bars', [
    c('&', { '--dsh-scrollbar-thumb': 'transparent', '--dsh-scrollbar-thumb-hover': 'transparent' }),
  ]),
  m('fading', [
    c('& > *', { opacity: 0, transition: 'opacity .15s var(--ds-ease-in-out)' }),
  ]),
  c('@keyframes dshp-rail-in', [c('from', { opacity: 0, transform: 'translate(49px)' })]),
  c('@keyframes dshp-rail-fade-in', [c('from', { opacity: 0 })]),
  c('@media (prefers-reduced-motion: reduce)', [
    c('.dshp-panel--fading > *', { transition: 'none' }),
    c('.dshp-panel--rail-in .dshp-panel__icon-button, .dshp-panel--rail-in .dshp-panel__menu-item, .dshp-panel--rail-in .dshp-panel__foot-area, .dshp-panel--rail-in .dshp-panel__region-area', { animation: 'none' }),
  ]),
])
